### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by thibmeu** [libp2p/go-doh-resolver#15]
A release would add the option to set max cache TTL.

Considering this provides a new feature, I suggest a feature release (v0.4.0) over a patch release (v0.3.2).

**Comment by marten-seemann** [comment]
Can you open PR that bumps the version number in `version.json`? We recently introduced workflows to automate our release process.

**Comment by thibmeu** [comment]
@marten-seemann thanks for the help on the release process. I opened a PR to bump the version to v0.4.0.
